on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: playwright-cache
        with:
          path: /Users/runner/Library/Caches/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/bun.lock') }}

      - name: Install dependencies
        run: bun ci

      - name: Install Playwright binaries
        run: bunx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run unit tests
        run: bun run test:types

      - name: Run e2e tests
        run: bun run test:e2e

      - name: Build docs
        if: github.ref == 'refs/heads/master'
        run: bun run build

      - name: Deploy docs
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
